name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b327d94d7ec5419ba78d6a2f027a597f3b7060dc429c4c75ba4f1436971b97a6"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
