name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36d824ade106f9590cbd715a1d6c6c74b69edbdfa9246284fe443337c2d3ef54"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
