name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f17601c783bcb2dfb7d5ef35d2537616eedc694beb291b53fd2ea271e2df1c20"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
