name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5283d7db9ddc0fcc9199b392de09cad307e4ec59f98608c1512cb6e3d9a7ee8"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
