name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df98478df68159b95b7dbf3148aa0c0319994d5be57cb7ad92a2ca7adf0cc030"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
